site_name: Welcome to Erick's PEcAn GSoC project 
site_url: https://ecamo19.github.io/gsoc2022_web/

theme:
  logo: images/favicon2.png
  favicon: images/favicon3.png
  name: material
  features:
    - content.tabs.link
  palette: 
     primary: green
     accent: blue
     
  
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
